"""     @author: Guang Yang
        @mktime: 2/7/2015
        @description: ladder maps and their url
"""
ladder_maps = {
    "Akilon Wastes": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/akilon_wastes.jpg",
    "Alterzim Stronghold TE": "",
    "Antiga Shipyard": "",
    "Bel'Shir Vestige": "",
    "Catallena": "",
    "Cloud Kingdom": "",
    "Daedalus Point": "",
    "Daybreak LE": "",
    "Deadwing LE": "",
    "Derelict Watcher TE": "",
    "Expedition Lost": "",
    "Fractured Glacier": "",
    "Foxtrot Labs LE": "",
    "Frost LE": "",
    "Habitation Station LE": "",
    "Heavy Rain LE": "",
    "Howling Peak": "",
    "Inferno Pools": "",
    "King Sejong Station LE": "",
    "Klontas Mire TE": "",
    "Korhal City": "",
    "Korhal Sky Island LE": "",
    "Merry Go Round LE": "",
    "Metalopolis": "",
    "Neo Planet S LE": "",
    "Newkirk Precinct": "",
    "Newkirk Precinct TE": "",
    "Nimbus LE": "",
    "Ohana LE": "",
    "Overgrowth LE": "",
    "Polar Night LE": "",
    "Red City LE": "",
    "Secret Spring": "",
    "Shakuras Plateau": "",
    "Star Station": "",
    "Star Station TE": "",
    "Vaani Research Station": "",
    "Waystation": "",
    "Whirlwind LE": "",
    "Xel'Naga Caverns": "",
    "Yeonsu LE": "",
    "Zerus Prime TE": "",
}
