"""     @author: Guang Yang
        @mktime: 2/7/2015
        @description: ladder maps and their url
"""
ladder_maps = {
    "Akilon Wastes": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/akilon_wastes.jpg",
    "Alterzim Stronghold TE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Alterzim_Stronghold_TE.jpg",
    "Antiga Shipyard": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Antiga_Shipyard.jpg",
    "Bel'Shir Vestige LE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Belshir_Vestige_LE.jpg",
    "Catallena LE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Catallena_LE.jpg",
    "Cloud Kingdom LE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Cloud_Kingdom_LE.jpg",
    "Daedalus Point": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Daedalus_Point.jpg",
    "Daybreak LE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Daybreak_LE.jpg",
    "Deadwing LE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Deadwing_LE.jpg",
    "Derelict Watcher TE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Derelict_Watcher_TE.jpg",
    "Expedition Lost": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Expedition_Lost.jpg",
    "Fractured Glacier": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Fractured_Glacier.jpg",
    "Foxtrot Labs LE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Foxtrot_Labs_LE.jpg",
    "Frost LE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Frost_LE.jpg",
    "Habitation Station LE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Habitation_Station_LE.jpg",
    "Heavy Rain LE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Heavy_Rain_LE.jpg",
    "Howling Peak": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Howling_Peak.jpg",
    "Inferno Pools": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Inferno_Pools.jpg",
    "King Sejong Station LE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/King_Sejong_Station_LE.jpg",
    "Klontas Mire TE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Klontas_Mire_TE.jpg",
    "Korhal City": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Korhal_City.jpg",
    "Korhal Floating Island LE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Korhal_Floating_Island_LE.jpg",
    "Merry Go Round LE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Merry_Go_Round_LE.jpg",
    "Metalopolis": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Metalopolis.jpg",
    "Neo Planet S LE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Neo_Planet_S_LE.jpg",
    "Newkirk Precinct": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Newkirk_City.jpg",
    "Newkirk Precinct TE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Newkirk_City_TE.jpg",
    "Nimbus LE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Nimbus_LE.jpg",
    "Ohana LE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Ohana_LE.jpg",
    "Overgrowth LE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Overgrowth_LE.jpg",
    "Polar Night LE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Polar_Night_LE.jpg",
    "Red City LE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Red_City_LE.jpg",
    "Secret Spring": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Secret_Spring.jpg",
    "Shakuras Plateau": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Shakuras_Plateau.jpg",
    "Star Station": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Star_Station.jpg",
    "Star Station TE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Star_Station_TE.jpg",
    "Vaani Research Station": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Vaani_Research_Station.jpg",
    "Waystation": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Waystation.jpg",
    "Whirlwind LE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Whirlwind_LE.jpg",
    "Xel'Naga Caverns": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Xel%27Naga_Caverns.jpg",
    "Yeonsu LE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Yeonsu_LE.jpg",
    "Zerus Prime TE": "https://s3-us-west-1.amazonaws.com/guang-stargazer/ladder_maps/Zerus_Prime_TE.jpg",
}
